require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
      - 'bin/**/*'
      - 'node_modules/**/*'
      - 'test/**/*'
      - 'db/schema.rb'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/views/**/*'
    - 'spec/system/**/*'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/system/**/*'

